export default {
	ADD_TODO_DIALOG_TITLE: "Add To-Do",
	EDIT_TODO_DIALOG_TITLE: "Edit To-Do",
	DIALOG_OK_BUTTON: "Ok",
	DIALOG_CANCEL_BUTTON: "Cancel",
	TODO_ITEM_SWITCH_LABEL: "Done:",
	EMPTY_TODO_LIST_MESSAGE: "You Don't Have Any To-Do Item"
};
